import{g as S,A as I,S as B,a as C,i as g}from"./assets/vendor-2EVeJbXo.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();new S({elements_selector:".lazy"});const f="/js-winners-team/assets/power-puls-CAR0I2Hr.png",P="/js-winners-team/assets/power-puls@2x-DfqaEtzv.png",b="/js-winners-team/assets/mimino-DW-6eCSM.png",A="/js-winners-team/assets/mimino@2x-Ct__Kg0f.png",v="/js-winners-team/assets/ukranian-CWLdLCmZ.png",O="/js-winners-team/assets/ukranian@2x-HArDxWck.png",x="/js-winners-team/assets/vegetables-DlrhDgVy.png",R="/js-winners-team/assets/vegetables@2x-qHKRnh7C.png",y="/js-winners-team/assets/finances-0s2aRETz.png",W="/js-winners-team/assets/finances@2x-CHWYYREp.png",h="/js-winners-team/assets/face-DW0gD83_.png",z="/js-winners-team/assets/face@2x-D4X0Y-PD.png",k="/js-winners-team/assets/body-BfEj9f96.png",H="/js-winners-team/assets/body@2x-BZl3QsGP.png",_="/js-winners-team/assets/fruits-6id4-Z-o.png",T="/js-winners-team/assets/fruits@2x-CWBpmrvj.png",j="/js-winners-team/assets/english-OAl_yic7.png",G="/js-winners-team/assets/english@2x-CyukS5XP.png",D="/js-winners-team/assets/busines-B8XQfsSH.png",M="/js-winners-team/assets/busines@2x-BcBZRin9.png",V=[{src:f,srcset:`${f} 1x, ${P} 2x`,alt:"A girl training at 'PowerPuls' gym"},{src:b,srcset:`${b} 1x, ${A} 2x`,alt:"White title on black, left side shows a hotel facade"},{src:v,srcset:`${v} 1x, ${O} 2x`,alt:"Girl in embroidered shirt on gray"},{src:x,srcset:`${x} 1x, ${R} 2x`,alt:"Basket of vegetables on green"},{src:y,srcset:`${y} 1x, ${W} 2x`,alt:"Couple with laptop, credit card"},{src:h,srcset:`${h} 1x, ${z} 2x`,alt:"Woman's face on brown, white title"},{src:k,srcset:`${k} 1x, ${H} 2x`,alt:"Girl with dumbbells, black title"},{src:_,srcset:`${_} 1x, ${T} 2x`,alt:"Title with orange, citrus fruits"},{src:j,srcset:`${j} 1x, ${G} 2x`,alt:"Schoolgirl writing at desk"},{src:D,srcset:`${D} 1x, ${M} 2x`,alt:"White title on black background"}],Z=e=>`
    <li class="covers-gallery-item">
            <picture class="covers-img">
              <source media="(min-width: 768px)"
                srcset="${e.srcset}" 
                width="544" 
                height="314" />
              <source media="(min-width: 320px)" 
                srcset="${e.srcset}" 
                width="282" 
                height="163" />
              <img src="${e.src}" alt="${e.alt}" />
            </picture>
          </li>
    `,K=(e,s)=>{const n=[];for(let i=0;i<s;i++)n.push(Z(e[i%e.length]));return n.join("")},E=()=>{const e=window.innerWidth;let s=40;e>=1024&&(s=50);const n=K(V,s),i=document.querySelector(".covers-gallery-js");i&&(i.innerHTML=n)};window.addEventListener("load",E);window.addEventListener("resize",E);document.addEventListener("DOMContentLoaded",function(){const e=Array.from(document.querySelectorAll(".accordion-container"));new I(e,{duration:400,showFirstItem:!1,elementClass:"faq-item",triggerClass:"faq-btn",panelClass:"faq-box-answer",headerClass:"faq-item-title",beforeOpen:s=>{const n=s.querySelector(".faq-box-answer");n.style.display="block"},beforeClose:s=>{const n=s.querySelector(".faq-box-answer");n.style.display="none"}})});const X=document.querySelectorAll(".faq-item");X.forEach(e=>{e.addEventListener("click",function(){this.querySelector(".faq-arrow").classList.toggle("rotate")})});const Y=document.querySelector(".desktop-menu-btn"),F=document.querySelector(".navigation-menu");Y.addEventListener("click",()=>{F.classList.toggle("is-open")});new B(".swiper",{keyboard:{enabled:!0,onlyInViewport:!1},navigation:{nextEl:".right-button",prevEl:".left-button"}});console.log("Hello!");C.defaults.baseURL="https://portfolio-js.b.goit.study/api";async function N(){const e=document.querySelector(".js-text-error"),s=document.querySelector(".js-reviews-btn");try{const n=await C.get("/reviews");if(n.data.length===0){s.classList.add("reviews__error"),e.classList.remove("reviews__error"),g.error({message:"Oops...Something went wrong!",position:"bottomRight"});return}return n.data}catch{s.classList.add("reviews__error"),e.classList.remove("reviews__error"),g.error({message:"Oops...Something went wrong!",position:"bottomRight"})}}const Q=new S({elements_selector:".lazy"}),U=document.querySelector(".js-reviews"),$={prevButton:document.querySelector(".reviews__btn--prev"),nextButton:document.querySelector(".reviews__btn--next"),prevIcon:document.querySelector(".js-review-icon-prev"),nextIcon:document.querySelector(".js-review-icon-next")},q={disabledBtnClass:"reviews__btn--disabled",disabledIconClass:"reviews__icon--disabled",disabledAttribute:"disabled"};function J(){new B(".swiper",{keyboard:{enabled:!0,onlyInViewport:!1},navigation:{nextEl:".reviews__btn--next",prevEl:".reviews__btn--prev"},breakpoints:{320:{slidesPerView:1,spaceBetween:16},375:{slidesPerView:1,spaceBetween:16},768:{slidesPerView:2,spaceBetween:16},1440:{slidesPerView:4,spaceBetween:16}},on:{init:function(){L(this,$,q)},slideChange:function(){L(this,$,q)}}})}window.onload=async()=>{const e=await N();se(ee,e),J(),Q.update()};function ee(e){return e.map(s=>`
        <li class="reviews__item swiper-slide">
            <img 
                class="lazy reviews__image"
                data-src="${s.avatar_url}" 
                alt="commentator's photo" 
            />
            <h4 class="reviews__title">${s.author}</h4>
            <p class="reviews__text">${s.review}</p>
        </li>`).join("")}function se(e,s){U.insertAdjacentHTML("beforeend",e(s))}function L(e,s,n){const{prevButton:i,nextButton:t,prevIcon:r,nextIcon:o}=s,{disabledBtnClass:u,disabledIconClass:w,disabledAttribute:p}=n,l=(a,d,c)=>{d?a.classList.add(c):a.classList.remove(c)},m=(a,d,c)=>{d?a.setAttribute(c,"true"):a.removeAttribute(c)};l(i,e.isBeginning,u),l(r,e.isBeginning,w),m(i,e.isBeginning,p),l(t,e.isEnd,u),l(o,e.isEnd,w),m(t,e.isEnd,p)}
//# sourceMappingURL=index.js.map
